# Generated by Django 3.0 on 2022-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couse_name', models.CharField(max_length=255)),
                ('couse_videos', models.CharField(max_length=255)),
                ('couse_video_title', models.CharField(max_length=255)),
                ('couse_video_description', models.CharField(max_length=255)),
                ('couse_video_url', models.CharField(max_length=2083)),
                ('couse_image_url', models.CharField(max_length=2083)),
                ('couse_video_owner', models.CharField(max_length=255)),
                ('couse_video_duration', models.CharField(max_length=255)),
            ],
        ),
    ]
