# Generated by Django 3.0 on 2022-04-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_courseimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReciever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.CharField(max_length=255)),
                ('send_message', models.CharField(max_length=4000)),
            ],
        ),
    ]
